Update examples to support latest Psydac and python3.12
pyccel/IGA-Python pull request #9
Opened 2024-11-27 11:45 UTC by kvrigor

It might be a good idea to externally link the [IGA Python docs](https://pyccel.github.io/IGA-Python/intro.html) from the [Psydac API docs](https://pyccel.github.io/psydac/examples.html). As a first step I'm making sure that all examples in this repository work with the latest version of Psydac.

2024-12-04 15:47 UTC, kvrigor commented
This PR is ready for review! Here are the summary of changes:

- Updated [`deploy-book.yml`](https://github.com/kvrigor/IGA-Python/blob/build-ci-update/.github/workflows/deploy-book.yml) to use the latest version of Psydac. Also simplified Psydac installation.
- Removed duplicate `keywords` field in `references.bib` since `jupyter-book` complains about them.
- Using [`nb-clean`](https://github.com/srstevenson/nb-clean), all Jupyter notebooks in this repo have been scrubbed free of data (e.g. cell execution count, cell result, path to Python environment, etc.) which shouldn't be tracked in `git`. The [Build Jupyter Book step](https://github.com/pyccel/IGA-Python/pull/9/checks#step:6:1) already handles the execution and rendering of these notebooks online.
- Updated the [Installation guide](https://github.com/kvrigor/IGA-Python/blob/build-ci-update/chapter1/install.md).

2025-02-12 10:38 UTC, kvrigor commented
Tagging @ratnania and @yguclu --- I hope you take a look at this PR.. thanks!

2025-02-12 11:44 UTC, yguclu requested changes
Looks good! I have just a couple of comments

2025-02-12 11:44 UTC, yguclu commented on .github/workflows/deploy-book.yml
> +        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Missing newline at end of file

2025-02-12 11:44 UTC, yguclu commented on requirements.txt
> +psydac[extra] @ git+https://github.com/pyccel/psydac.git@devel#egg=psydac
What does this `[extra]` mean?

BTW the end of file is missing a newline character.

2025-02-12 13:51 UTC, campospinto commented
Thanks @kvrigor ! I have a few questions:

- With these changes are all the notebooks tested in the CI ?

- I tried to follow the installation instructions from [install.md](https://github.com/kvrigor/IGA-Python/blob/build-ci-update/chapter1/install.md) and I get an error (see below): is this because I am using a mac (for which the installation is not tested), or because the CI and the `install.md` do not agree ?

```
INFO: pip is looking at multiple versions of psydac to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement sympde==0.19.0 (from psydac) (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.17.0, 0.17.1)
ERROR: No matching distribution found for sympde==0.19.0
```

2025-02-12 14:54 UTC, yguclu commented
> * I tried to follow the installation instructions from [install.md](https://github.com/kvrigor/IGA-Python/blob/build-ci-update/chapter1/install.md) and I get an error (see below): is this because I am using a mac (for which the installation is not tested), or because the CI and the `install.md` do not agree ?
> 
> 
> ```
> INFO: pip is looking at multiple versions of psydac to determine which version is compatible with other requirements. This could take a while.
> ERROR: Could not find a version that satisfies the requirement sympde==0.19.0 (from psydac) (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.17.0, 0.17.1)
> ERROR: No matching distribution found for sympde==0.19.0
> ```

Good point @campospinto, the build of the Jupyter book should probably be tested on multiple platforms.

As for the error, I do not see a substantial difference between the instructions in `deploy-book.yml` and those in `install.md`. They both use a virtual environment (one provided automatically by GitHub, the other manually created by the user) and install Psydac as a dependency through our `requirements.txt` file. The CI updates `pip` before installing, though...

2025-02-12 16:30 UTC, campospinto commented
> Good point @campospinto, the build of the Jupyter book should probably be tested on multiple platforms.
> 
> As for the error, I do not see a substantial difference between the instructions in `deploy-book.yml` and those in `install.md`. They both use a virtual environment (one provided automatically by GitHub, the other manually created by the user) and install Psydac as a dependency through our `requirements.txt` file. The CI updates `pip` before installing, though...

alright, then can you add a macos test @kvrigor ? If it passes, I'll try again to install on my mac.

2025-02-19 12:38 UTC, kvrigor commented on .github/workflows/deploy-book.yml
> +        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Fixed

2025-02-19 12:39 UTC, kvrigor commented on requirements.txt
> +psydac[extra] @ git+https://github.com/pyccel/psydac.git@devel#egg=psydac
`[extra]` is a [dependency specifier](https://packaging.python.org/en/latest/specifications/dependency-specifiers/#extras) which basically installs optional features of a package. I have removed it since the `jupyterbook build` seems to succeed even without it.

2025-02-19 12:42 UTC, kvrigor commented
@campospinto I have added a macOS test and it passes. As for your questions:

> With these changes are all the notebooks tested in the CI ?

Yes; this is performed during the [Build Jupyter Book step](https://github.com/pyccel/IGA-Python/actions/runs/13412332443/job/37465159956?pr=9#step:9:177).
 
> should one use nb-clean before every commit of a notebook ?

Yes; otherwise irrelevant changes such as cell counts, metadata, etc. would show up in `git diff`. `nb-clean`  [can be automated](https://github.com/srstevenson/nb-clean#cleaning-git-filter) by running:

```bash
# Apply nb-clean filter on a specific git repo
cd IGA-Python

# Automatically removes cell execution counts, metadata, outputs,
# and empty cells of `git add`-ed `.ipynb` files.
nb-clean add-filter --remove-empty-cells
```

> I tried to follow the installation instructions from install.md and I get an error (see below): is this because I am using a mac (for which the installation is not tested), or because the CI and the install.md do not agree ?

This seems to be an issue when using `python3.13`. Please retry with `python3.12` or lower.

2025-02-19 15:17 UTC, kvrigor commented
@yguclu I have removed the author info in [ac30ed9](https://github.com/pyccel/IGA-Python/pull/9/commits/ac30ed990d016073bfd04ed10901d5a5e5e87f55).

2025-02-19 15:44 UTC, yguclu requested changes

2025-02-19 15:44 UTC, yguclu commented on intro.md
> -*Author: Ahmed Ratnani*
We should probably keep the authors' names in this first page of the "book". To this end we can list all contributors in an AUTHORS.md file, the contents of which could be displayed here. Ahmed should be the first author as he is the one who started the project.

2025-02-25 15:19 UTC, kvrigor commented on intro.md
> -*Author: Ahmed Ratnani*
I've just added an `AUTHORS` file and now it looks like this: ![intro](https://github.com/user-attachments/assets/d27a7488-6c76-4df3-b0e2-18a1924fabd5)

Unfortunately the `AUTHORS` file can't be written as one-line per author. Doing so renders the list of authors in a single line (without delimiters). Maybe there's a workaround, but so far I haven't found any solution from the [MyST docs](https://myst-parser.readthedocs.io/en/latest/faq/index.html#include-rst-files-into-a-markdown-file).

2025-02-25 15:20 UTC, kvrigor commented
I've also updated the `README` file and can be viewed here: https://github.com/kvrigor/IGA-Python/tree/build-ci-update?tab=readme-ov-file

2025-02-25 15:43 UTC, yguclu commented on intro.md
> -*Author: Ahmed Ratnani*
I see. Then I suggest that we leave only Ahmed as author here, and add a link to the complete AUTHORS file, maybe in the footnote. How does that sound to you?

2025-02-25 15:49 UTC, yguclu requested changes

2025-02-25 15:49 UTC, yguclu commented on Makefile
> +	jupyter-book clean .
Missing newline at end of file

2025-02-25 15:49 UTC, yguclu commented on AUTHORS
> +Ahmed Ratnani, Mohamed Jalal Maaouni
See my comment [here](https://github.com/pyccel/IGA-Python/pull/9#discussion_r1970045013): please format this file as standard with one author per line.

Also a newline character is missing at the end of the file.

2025-02-26 11:20 UTC, kvrigor commented on AUTHORS
> +Ahmed Ratnani, Mohamed Jalal Maaouni
Fixed

2025-02-26 11:20 UTC, kvrigor commented on Makefile
> +	jupyter-book clean .
Fixed

2025-02-26 11:22 UTC, kvrigor commented on intro.md
> -*Author: Ahmed Ratnani*
Sounds good! I've already made the changes:

![image](https://github.com/user-attachments/assets/88a561cc-a7c5-4def-b488-9dcb698ce38e)
![image](https://github.com/user-attachments/assets/8b9a5c78-00ae-4649-a73c-3d2dba64d860)

2025-02-26 12:36 UTC, campospinto commented
> I've also updated the `README` file and can be viewed here: https://github.com/kvrigor/IGA-Python/tree/build-ci-update?tab=readme-ov-file

Thanks Paul! 

I have another question: when installing the dependencies, do you know if psydac is (re)installed ? 

In particular, Is there a simple way to be sure that you will be using your psydac version, if you previously had one installed?

2025-02-26 13:08 UTC, yguclu commented on intro.md
> -*Author: Ahmed Ratnani*
That looks great!

2025-02-26 13:09 UTC, yguclu commented on AUTHORS
> +Ahmed Ratnani, Mohamed Jalal Maaouni
You should add your name to the AUTHORS

2025-02-26 13:40 UTC, kvrigor commented
> I have another question: when installing the dependencies, do you know if psydac is (re)installed ?

@campospinto Since psydac is declared as a git repo in [`requirements.txt`](https://github.com/pyccel/IGA-Python/blob/c4b0a9f4a6692d879da00bb7e080c340fa1d67bd/requirements.txt#L8), I'd assume that it could be re-installed whenever psydac `devel` gets updated. 

> In particular, Is there a simple way to be sure that you will be using your psydac version, if you previously had one installed?

Yes--by editing [`requirements.txt`](https://github.com/pyccel/IGA-Python/blob/c4b0a9f4a6692d879da00bb7e080c340fa1d67bd/requirements.txt#L8)  and then pointing psydac to a  [git commit hash](https://pip.pypa.io/en/stable/topics/vcs-support/#git), e.g.:

```
psydac @ git+https://github.com/pyccel/psydac.git@5ff388417225f5fb7a6e1ec1c4490d2fb48233f5
```

2025-02-26 14:19 UTC, campospinto commented
> > I have another question: when installing the dependencies, do you know if psydac is (re)installed ?
> 
> @campospinto Since psydac is declared as a git repo in [`requirements.txt`](https://github.com/pyccel/IGA-Python/blob/c4b0a9f4a6692d879da00bb7e080c340fa1d67bd/requirements.txt#L8), I'd assume that it could be re-installed whenever psydac `devel` gets updated.
> 
> > In particular, Is there a simple way to be sure that you will be using your psydac version, if you previously had one installed?
> 
> Yes--by editing [`requirements.txt`](https://github.com/pyccel/IGA-Python/blob/c4b0a9f4a6692d879da00bb7e080c340fa1d67bd/requirements.txt#L8) and then pointing psydac to a [git commit hash](https://pip.pypa.io/en/stable/topics/vcs-support/#git), e.g.:
> 
> ```
> psydac @ git+https://github.com/pyccel/psydac.git@5ff388417225f5fb7a6e1ec1c4490d2fb48233f5
> ```

I see. And would it also work if one simply removes this line in his `requirements.txt` file ?

2025-02-27 07:40 UTC, campospinto commented on README.md
> +# Install dependencies on a virtual environment
I suggest to mention here the possibility of not reinstalling psydac:
```suggestion
# Install dependencies on a virtual environment 
# (note: to use a version of psydac that is already installed, remove the corresponding line in the requirements.txt file) ```

2025-02-27 08:26 UTC, yguclu commented on README.md
> +# Install dependencies on a virtual environment
I agree with this suggestion. In the future we aim at a proper versioning of Psydac, which could be downloaded from PyPI. Hence the `requirements.txt` file would only contain the line `psydac`, which would not force a reinstallation of the library.

2025-02-27 08:33 UTC, kvrigor commented on README.md
> +# Install dependencies on a virtual environment
I have an easier way to skip the psydac installation step 😉 see the latest changes at https://github.com/kvrigor/IGA-Python/tree/build-ci-update?tab=readme-ov-file

2025-02-27 10:28 UTC, yguclu commented on README.md
> +# Install dependencies on a virtual environment
That works for me. What do you think, @campospinto?

2025-02-27 15:10 UTC, campospinto commented on README.md
> +# Install dependencies on a virtual environment
Yes, this seems fine, thanks!

2025-02-27 15:13 UTC, campospinto commented on README.md
> +# Install dependencies on a virtual environment
But the file `chapter1/install.md` still has the old installation instructions, they should probably be removed

2025-02-28 07:57 UTC, kvrigor commented on README.md
> +# Install dependencies on a virtual environment
> But the file `chapter1/install.md` still has the old installation instructions, they should probably be removed

You might be seeing the version from `master` branch. Here is the version from my branch / this PR: https://github.com/kvrigor/IGA-Python/blob/build-ci-update/chapter1/install.md

2025-02-28 08:03 UTC, campospinto commented on README.md
> +# Install dependencies on a virtual environment
Well, I see some (old) installation commands here: 
https://github.com/kvrigor/IGA-Python/blob/build-ci-update/chapter1/install.md#installation

The installation commands should only be written once (the README seems a good place), and a pointer (to the README) could be given in the chapter 1.

2025-02-28 08:42 UTC, kvrigor commented on README.md
> +# Install dependencies on a virtual environment
> The installation commands should only be written once (the README seems a good place), and a pointer (to the README) could be given in the chapter 1.

Ah I see! The install steps in `install.md` and `README`, while having the same goals, are written for 2 different audiences: general users and developers. My assumption is that `install.md` would be most likely accessed from the IGA-Python site and will be read by a broad range of users. In contrast, `README` would be most likely be accessed by developers, and thus written in a concise way which assumes more background knowledge.

2025-02-28 08:50 UTC, kvrigor commented on README.md
> +# Install dependencies on a virtual environment
Also, `install.md` and `README` have slightly different goals: the former is for users who may be learning Psydac for the first time and expects a quick and easy way to try it, while the latter is for more advanced users who may also potentially contribute to the repo.

2025-02-28 09:41 UTC, campospinto commented on README.md
> +# Install dependencies on a virtual environment
Ok, indeed this can justify two sets of install instructions. Still, for people who want to try these examples with their own, already installed version of psydac (which might include non developers) , I would mention the possibility of not reinstalling psydac in `chapter1/install.md`

2025-02-28 10:17 UTC, kvrigor commented on README.md
> +5. View your changes on the browser: `open _build/html/index.html`
Good point! `nb-clean` is only necessary when committing to source control. Maybe it's a good idea to add a "Contributing" section to the README?

2025-02-28 10:24 UTC, kvrigor commented on README.md
> +4. Build the docs by running `make`.
`make` is a directory-sensitive command: it checks for a file named `Makefile` in the current directory and then executes it.  Running `make` under the `IGA-Python` directory (note that `cd IGA-Python` was done in Step 1) executes the topmost-defined target in this [`Makefile`](https://github.com/kvrigor/IGA-Python/blob/0473381a7ff79c32c435efde3e525721a9b6187a/Makefile#L4). I would update the README to make this clearer.

2025-02-28 10:30 UTC, kvrigor commented on README.md
> +Contains the source code of the [IGA-Python](https://pyccel.github.io/IGA-Python/) site.
I admit this was lazily written sentence 😅

Can you suggest a better introductory text? The IGA-Python homepage says "*Welcome to IGA-Python, a tutorial for Isogeometric Analysis using Python*", but I'm not sure if that's a fitting intro in the `README` as well.

2025-02-28 10:35 UTC, kvrigor commented on README.md
> +3. Edit the desired Python notebooks (`*.ipynb`) and/or Markdown files (`*.md`). Check the [MyST syntax cheat sheet](https://jupyterbook.org/en/stable/reference/cheatsheet.html) for reference.
It depends on the user's goal: either the user wants to run the notebooks individually (which I assume they already know how), or the user wants to build all notebooks with the purpose of contributing to this repo. I will add a "Contributing" section so these two cases are clearly distinguished.

2025-02-28 10:45 UTC, campospinto commented on README.md
> +5. View your changes on the browser: `open _build/html/index.html`
Well, not really: if you run the notebooks and try to pull an updated version of IGA-Python afterwards, git will (may?) scream at you because you have modifications that will be overwritten. Of course you can stash them, but this might scare off new users

2025-02-28 11:08 UTC, kvrigor commented on README.md
> +5. View your changes on the browser: `open _build/html/index.html`
Ah you're right--a dirty staging area is a common cause of headache 😅 I will add a `make` rule to easily clean edited notebooks 😃

2025-02-28 16:53 UTC, campospinto commented on README.md
> +Contains the source code of the [IGA-Python](https://pyccel.github.io/IGA-Python/) site.
I suggest something like:

```
This project provides a tutorial for isogeometric Finite Elements, with numerical illustrations using the [Psydac library](https://github.com/pyccel/psydac). The examples can either be consulted online on https://pyccel.github.io/IGA-Python, or installed as notebooks and run on a personal computer.
```
@yguclu do you agree with this description ?

2025-03-03 17:06 UTC, yguclu commented on README.md
> +Contains the source code of the [IGA-Python](https://pyccel.github.io/IGA-Python/) site.
Yes, mostly. I suggest this:

> This project provides a tutorial for isogeometric analysis (IGA) using Python and the Psydac library (https://github.com/pyccel/psydac). The numerical examples can be consulted online at https://pyccel.github.io/IGA-Python, or run with Jupyter Notebook on a personal computer.

2025-03-04 12:53 UTC, kvrigor commented on README.md
> +Contains the source code of the [IGA-Python](https://pyccel.github.io/IGA-Python/) site.
> Yes, mostly. I suggest this:
> 
> > This project provides a tutorial for isogeometric analysis (IGA) using Python and the Psydac library ([pyccel/psydac](https://github.com/pyccel/psydac?rgh-link-date=2025-03-03T17%3A06%3A22Z)). The numerical examples can be consulted online at [pyccel.github.io/IGA-Python](https://pyccel.github.io/IGA-Python), or run with Jupyter Notebook on a personal computer.

I have updated `README` following this suggestion.

2025-03-04 13:01 UTC, kvrigor commented on README.md
> +3. Edit the desired Python notebooks (`*.ipynb`) and/or Markdown files (`*.md`). Check the [MyST syntax cheat sheet](https://jupyterbook.org/en/stable/reference/cheatsheet.html) for reference.
Here's the [updated version](https://github.com/kvrigor/IGA-Python/tree/build-ci-update?tab=readme-ov-file#editing-and-building-iga-python-locally):

```md
31  3. Run or modify the desired Python notebooks (`*.ipynb`) and Markdown files (`*.md`). Check the [MyST syntax cheat sheet](https://jupyterbook.org/en/stable/reference/cheatsheet.html) for reference.
32
33  > [!NOTE]  
34  > Before committing changes to git, the notebooks have to be cleaned first. See ["Committing your changes to git"](#committing-your-changes-to-git) for more information.
```

2025-03-04 13:02 UTC, kvrigor commented on README.md
> +4. Build the docs by running `make`.
Here's the [updated version](https://github.com/kvrigor/IGA-Python/tree/build-ci-update?tab=readme-ov-file#editing-and-building-iga-python-locally):

```md
36  4. Build the docs by running `make` under the IGA-Python folder. This involves running all `*.ipynb` files in the background to make sure they are functional.
37
38  ```bash
39  cd ${IGA_PYTHON_DIR}
40  make
41  ```
```

2025-03-04 13:17 UTC, kvrigor commented on README.md
> +# Install dependencies on a virtual environment
> Ok, indeed this can justify two sets of install instructions. Still, for people who want to try these examples with their own, already installed version of psydac (which might include non developers) , I would mention the possibility of not reinstalling psydac in `chapter1/install.md`

Fixed here: [chapter1/install.md](https://github.com/kvrigor/IGA-Python/blob/build-ci-update/chapter1/install.md#installation)

2025-03-04 15:13 UTC, campospinto commented
Thanks Paul for the changes!

2025-03-05 13:14 UTC, campospinto approved these changes

2025-03-05 18:52 UTC, merged